module.exports = [
    {
        title: 'Angel Miners and the Lightning',
        artist: 'AWOLNATION',
        genre: 'Alt Rock',
        yearReleased: 2020,
        dateFinished: `May 7, 2020`,
        img: 'https://images-na.ssl-images-amazon.com/images/I/61F5kfkqt3L._SY355_.jpg',
        review: `Listened to this at the insistence of a friend, especially the track 
    'I'm In My Head'. Always love AWOL. I don't listen to them enough.`,
    rating: 5,
    },
    {
        title: `Fetch the Bolt Cutters`,
        artist: `Fiona Apple`,
        genre: `Experimental`,
        yearReleased: 2020,
        dateFinished: `May 7, 2020`,
        img: 'https://m.media-amazon.com/images/I/61fe8iuUHKL._SS500_.jpg',
        review: `I'll put in an actual review later.`,
        rating: 5,
    },
    {
        title: 'Float',
        artist: `Flogging Molly`,
        genre: `Irish Punk`,
        yearReleased: 2008,
        dateFinished: `April 22, 2020`,
        img: 'https://m.media-amazon.com/images/I/A1nmbwrMbmL._AC_UL320_.jpg',
        review: `This one holds a special place in my heart.`,
        rating: 5,
    },
    {
        title: `While I'm Livin'`,
        artist: `Tanya Tucker`,
        genre: `Country`,
        yearReleased: 2019,
        dateFinished: `April 22, 2020`,
        img: 'https://images-na.ssl-images-amazon.com/images/I/71WV8FmOGqL._SY355_.jpg',
        review: `Holds up just as well as any of her older stuff. She puts a new twist on 'The House that Built Me' that I really love.`,
        rating: 4.5,
    },
    {
        title: `Claire and the Bears`,
        artist: `Claire and the Bears`,
        genre: `Alt-country rock`,
        yearReleased: 2019,
        dateFinished: `May 3, 2020`,
        img: `https://f4.bcbits.com/img/a0397572278_16.jpg`,
        review: `The album is good. I feel like from a production standpoint, they're still trying to figure out how to transfer the energy of their live performances into a studio album.`,
        rating: 4,
    },
]