module.exports = [
    {
    title: `11/22/63`,
    author: `Stephen King`,
    genre: `Science Fiction`,
    yearReleased: 2012,
    dateFinished: `2020`,
    img: 'https://images-na.ssl-images-amazon.com/images/I/51vTQSkTUlL._SX329_BO1,204,203,200_.jpg',
    review: `This is actually the third time I read this book. One of my favorites.`,
    rating: 5,
    },
    {
    title: `The Time Traveler’s Wife`,
    author: `Audrey Neffenegger`,
    genre: `Fantasy`,
    yearReleased: 2003,
    dateFinished: `2015`,
    img: `https://images-na.ssl-images-amazon.com/images/I/817iFfLhJ+L.jpg`,
    review: `Another one I’ve read multiple times. One of my favorites.`,
    rating: 5,
    },
    {
    title: 'The Art of Racing in the Rain',
    author: 'Garth Stein',
    genre: 'Fiction',
    yearReleased: 2008,
    dateFinished: 'Future Read',
    img:`https://m.media-amazon.com/images/I/41t4Svkx6KL._AC_UY436_FMwebp_QL65_.jpg`,
    review: `Haven't read yet, but looking forward to it.`,
    rating: 3,
    },
    {
     title: 'Sing in the Second City',
     author: 'Karen Abbott',
     genre: 'Historical Fiction',
     yearReleased: 2008,
     dateFinished: 'December 27th, 2019',
     img: 'https://m.media-amazon.com/images/I/51Z+ebJE1CL._AC_UY436_FMwebp_QL65_.jpg',
     review: `I guess I was expecting something more like 'Murder in the Second City', but enjoyed it nonetheless.`,
     rating: 3.5,  
    },
    {
    title: `The Worst Hard Time`,
    author: `Timothy Egan`,
    genre: 'Non-Fiction',
    yearReleased: 2006,
    dateFinished: 'February 11th, 2020',
    img: 'https://m.media-amazon.com/images/I/81ABZkfT-OL._AC_UY436_FMwebp_QL65_.jpg',
    review: 'A little dry and slow, but an informative read.',
    rating: 4,
    }
]